# Generated by Django 3.2.13 on 2022-04-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20220429_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='lyric',
            field=models.TextField(),
        ),
    ]
