# Generated by Django 3.2.5 on 2022-04-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_diary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='comment_TF',
            field=models.BooleanField(choices=[('True', '허용'), ('False', '비허용')], default=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='public_TF',
            field=models.BooleanField(choices=[('True', '공개'), ('False', '비공개')], default=True),
        ),
    ]
