# Generated by Django 3.2.5 on 2022-04-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20220422_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='comment_TF',
            field=models.BooleanField(choices=[(True, '허용'), (False, '비허용')], default=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='public_TF',
            field=models.BooleanField(choices=[(True, '공개'), (False, '비공개')], default=True),
        ),
    ]
