# Generated by Django 3.1.14 on 2022-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20220422_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
