# Generated by Django 3.2.13 on 2022-04-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20220427_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='vector',
            field=models.CharField(default=[0], max_length=65535),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
