# Generated by Django 3.1.14 on 2022-04-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20220427_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='emotion_value',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
