# Generated by Django 3.2.13 on 2022-04-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diary_emotion_value'),
        ('diary', '0007_diary_music_no'),
    ]

    operations = [
    ]
