# Generated by Django 3.1.14 on 2022-04-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_merge_0006_diary_emotion_value_0007_diary_music_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='emotion_value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='music_no',
            field=models.IntegerField(),
        ),
    ]
