# Generated by Django 3.2.5 on 2022-04-21 07:05

import Login.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임 입니다.'}, max_length=15, null=True, unique=True, validators=[Login.validators.validate_no_special_characters]),
        ),
    ]
