<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-04-29 08:17
=======
# Generated by Django 3.2.13 on 2022-04-30 08:13
>>>>>>> 7fbc34c6d68366273d7fe63a480f29013f54d857

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20220429_0125'),
        ('Login', '0008_alter_user_id'),
    ]

    operations = [
    ]
