# Generated by Django 3.2.13 on 2022-04-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20220429_0125'),
        ('Login', '0008_alter_user_id'),
    ]

    operations = [
    ]
