# Generated by Django 3.1.14 on 2022-04-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_calendar', '0006_auto_20220429_0125'),
        ('emotion_calendar', '0006_auto_20220429_0121'),
    ]

    operations = [
    ]
