# Generated by Django 3.2.13 on 2022-04-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_calendar', '0006_auto_20220429_0125'),
        ('emotion_calendar', '0007_alter_event_id'),
    ]

    operations = [
    ]
